### ISSUE TITLE
Kali Installation Script Broken

### ISSUE THREAD

**Issue by c0d3xpl0it** [jesusprubio/bluebox-ng#96]
Hello,

I am kali linux user. I found the URL:- https://raw.githubusercontent.com/jesusprubio/bluebox-ng/master/artifacts/installScripts/kali2.sh returns 404 error. Can you look in same.

**Comment by jesusprubio** [comment]
Sure, my fault. The reason is that we're finishing the new version and this part is still not done. We've already merged with master because this stable branch was also broken.

We hope everything is ready again in a couple of weeks.

Sorry for the inconvenience but we're doing this in our free time. :(
